AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.micro
      KeyName: ks_test # Replace with your key pair name
      ImageId: ami-04a81a99f5ec58529  # Replace with a valid AMI ID for your region
      SecurityGroups: 
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Enable SSH access
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
