# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty
version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudfromation Stack
          command: |
              aws cloudformation deploy --template-file template.yml --stack-name myStack-$(CIRCLE_WORKFLOW_ID:0:5) --region us-east-1
  configure_infrastructure:
    docker:
      - image: python:3.9-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprint: "SHA256:o/Law/xoaeC8TtrnABPSfNEWNhbWYv3QefFXNMKvadA"
      - run:
          name: Install Ansible
          command: |
              apk add --update ansible
      - run:
          name: Run Playbook and configure server
          command: |
              ansible-playbook -i inventory.txt main1.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="htpps://blog.udacity.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi

workflows:
  cft:
    jobs:
      - create_infrastructure
      # - configure_infrastructure:
      #     requires:
      #       - create_infrastructure
      - smoke_test
