# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty
version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudfromation Stack
          command: |
              aws cloudformation deploy --template-file template.yml --stack-name myStack-$(CIRCLE_WORKFLOW_ID:0:5) --region us-east-1
  configure_infrastructure:
    docker:
      - image: circleci/python:3.8-browsers
    steps:
      - checkout
      # - run:
      #     name: Add Missing Public Key
      #     command: |
      #       apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
      - run:
          name: Install SSH Client
          command: apt-get update && apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprint: ["SHA256:o/Law/xoaeC8TtrnABPSfNEWNhbWYv3QefFXNMKvadA"]
      - run:
          name: SSH into EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@107.23.116.15
      - run:
          name: Install Ansible
          command: |
              apk add --update ansible
      - run:
          name: Run Playbook and configure server
          command: |
              ansible-playbook -i inventory.txt main1.yml
workflows:
  cft:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires:
            - create_infrastructure
